---
title: JPE Replication Report
date: today
number-sections: true
format:
  html: default
---

# Paper Identification

|  |   |
| ---  |  -------|
| ID  |  {{< var paper_id >}} |
| Author  |  {{< var author >}} |
| Title  |  {{< var title >}} |
| Iteration |  {{< var round >}} |




Some useful information up front:

- [JPE Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy)
- [Step by step guidance from Data Editor for Authors](https://jpedataeditor.github.io/) 
- [Template README](https://social-science-data-editors.github.io/template_README/)


# Summary



In assessing compliance with our [Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy), our reproducibility team has identified the following issues, which we ask you to address:

1. You should include a better description of how to access the confidential data. Where is the URL / the contact address of the person to contact for this? What is the estimated time and monetary cost for the application?
2. The computational requirements are incomplete. You must describe in detail the machine where you last ran this, together with OS, stata version, etc. 

# General

- [X] Data Availability and Provenance Statements
  - [x] Statement about Rights - Part 1: Right to use the data (e.g. *did the authors lawfully obtain the data*)
  - [x] Statement about Rights - Part 2: Right to publish the data (e.g. *are human subjects involved and did permission been granted to publish their data?*)
  - [x] License for Data (optional, but recommended)
  - [x] Details on each Data Source
- [x] Dataset list
- [x] Computational requirements
  - [x] Software Requirements
  - [ ] Controlled Randomness (as necessary)
  - [x] Memory, Runtime, and Storage Requirements
- [x] Description of programs/code
  - [ ] License for Code (Optional, but recommended) 
- [x] {REPLICATOR} to Replicators
  - [ ] Details (as necessary)
- [x] List of tables and programs
- [ ] References (Optional, but recommended)    
    

# High-level Description of Research Project


*This research project...*

- [x] uses observational data.
- [x] uses *confidential* observational data.
- [ ] uses data generated via experiment or trial by the authors (in field or lab).
  - [ ] For lab experiments: The code to implement the experimental protocol (z-Tree, o-Tree etc) is included in the package.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF document outlining the design of the experiment, including information on the selection and eligibility of participants is included.
  - [ ] A PDF copy of the instructions given to participants in both original language and an English translation is included.
- [ ] uses data generated via survey by the authors (in field or online)
  - [ ] The programs used to administer the survey (e.g. qualtrics survey file) are included.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF of the original questionaire(s) and information on the selection and eligibility of participants is included.
- [ ] is a simulation study: the data are generated by an algorithm.
- [ ] is a numerical illustration: no data are used but code is used to produce illustrative output (tables, figures)


# Data description

For any data that cannot be provided as part of the replication package, please provide the following information as part of the README.

> {REQUIRED}  Please specify how long the data will be preserved in the restricted-access location.

> {REQUIRED} Please provide affirmation of support for replication checks.
  - As per the [JPE policy](https://jpedataeditor.github.io/policy.html), "In cases where data cannot be published in an openly accessible trusted data repository like the JPE dataverse, authors who have requested an exemption to publish them at the time of first submission must commit to preserving the data and code for a period of no less than five years following the publication of the paper. They should also provide reasonable assistance to requests for clarification and replication."


> {REQUIRED} Please provide a codebook for the data.
  - The codebook should at a minimum describe the variables obtained from the data source, in a manner that will let others verify that they have obtained a substantially similar dataset if successfully obtaining access to the data.


## Data Sources


| file/name                                               | public | private | DOI/URL | Access described | cited readme | cited paper |
|---------------------------------------------------------|--------|---------|---------|------------------|--------------|-------------|
| U.S. Census LFTTD + linked business microdata           | no     | yes     | yes     | yes              | no           | no          |
| BEA Gross Output by Industry (apparel, 1992–2015)       | yes    | no      | yes     | yes              | no           | no          |
| WTO clothing imports and exports (1992–2015)            | yes    | no      | yes     | yes              | no           | no          |
| OTEXA apparel imports by origin (1996–2011)             | yes    | no      | yes     | yes              | no           | no          |
| Annual Retail Trade Survey (ARTS, 1992–2022)            | yes    | no      | yes     | yes              | no           | no          |
| USITC DataWeb annual imports (2017–2025)                | yes    | no      | yes     | yes              | no           | no          |
| USITC annual tariffs & Section 301 analysis             | yes    | no      | yes     | yes              | no           | no          |


# Requirements 

- [x] README is in TXT, MD, or PDF format
- [x] README is accessible at the root of the package (not inside a folder)
- [x] Title conforms to guidance (starts with "Data and Code for: Title of Paper" or "Code for: Title of Paper", is properly capitalized)
- [x] Authors (with affiliations) are listed in the same order as on the paper



## Stated Requirements

The package was verified on 64-bit Linux with MATLAB R2025b, StataNow 19.5, and 8 MATLAB 
parallel workers. Required MATLAB products are MATLAB, Global Optimization Toolbox, and 
Parallel Computing Toolbox. Required Stata community packages are ebalance, ftools, 
require, and reghdfe.  The release archive is about 270 MB and expands to about 505 MB; 
allow at least 2 GB of free working space because MATLAB creates temporary working copies. A fast run takes about 8–10 minutes on the verification workstation.
All commands below assume the current directory is the package root. Paths are constructed relative to the package. Existing files under output/ are overwritten when regenerated.


For missing requirements, see the list of required changes in @sec-findings

# Analyzing Data and Code Files


{{< include generated/report-pii.md >}}

{{< include generated/report-file-paths.md >}}

{{< include generated/report-duplicates.md >}}

{{< include generated/report-zero-files.md >}}

{{< include generated/report-large-files.md >}}



## Code description

There is one master-matlab file and one separate Stata do-file. As said earlier there is no overview in the README that explains which lines of the script produce specific figures or tables.

{{< include generated/report-cloc.md >}}


- [x] The replication package contains a "main" or "master" file(s) which calls all other auxiliary programs.


> NOTE: In-text numbers that reference numbers in tables do not need to be listed. Only in-text numbers that correspond to no table or figure need to be listed.

## Computing Environment of the Replicator
- Nuvolos cloud 4vCPU & 16GB RAM


- Stata/MP 19.5
- Matlab R2025b

# Replication

- Downloaded code and data from dropbox
- Opened MATLAB per README
- Used the 'Bounded full-workflow' test for this replication
- ran the master-script and additional stata do-file per README


# Findings {#sec-findings}



- The issue I encountered earlier was resolved, did not encounter another issue.  


## Data Preparation Code

No raw data preparation code is included in this replication package. The authors have already processed the confidential data and provided the derived statistics needed for replication. The only code that needs to be run for this replication is the master script (run_all_replication.m) in MATLAB,this ran smoothly. 

## Tables and Figures

- Discrepancies found in the first version are now resolved, all generated output matches the output of the paper. 


## Other Issues

- Some small issues in the README remain. 

# Classification


- [x] full reproduction
- [ ] full reproduction with minor issues
- [ ] partial reproduction (see above)
- [ ] not able to reproduce most or all of the results (reasons see above)

## Reason for incomplete reproducibility

- [x] None.
- [ ] `Discrepancy in output` (either figures or numbers in tables or text differ)
- [ ] `Bugs in code` that were fixable by the replicator (but should be fixed in the final deposit)
- [ ] `Code missing`, in particular if it prevented the replicator from completing the reproducibility check
  - [ ] `Data preparation code missing` should be checked if the code missing seems to be data preparation code
- [ ] `Code not functional` is more severe than a simple bug: it prevented the replicator from completing the reproducibility check
- [ ] `Software not available to replicator` may happen for a variety of reasons, but in particular (a) when the software is commercial, and the replicator does not have access to a licensed copy, or (b) the software is open-source, but a specific version required to conduct the reproducibility check is not available.
- [ ] `Insufficient time available to replicator` is applicable when (a) running the code would take weeks or more (b) running the code might take less time if sufficient compute resources were to be brought to bear, but no such resources can be accessed in a timely fashion (c) the replication package is very complex, and following all (manual and scripted) steps would take too long.
- [ ] `Data missing` is marked when data *should* be available, but was erroneously not provided, or is not accessible via the procedures described in the replication package
- [ ] `Data not available` is marked when data requires additional access steps, for instance purchase or application procedure. 
- [ ] `Missing README` is marked if there is no README to guide the replicator, or the README is not in compliance with JPE requirements


{{< include generated/report-pii.md >}}