function generate_table_figure_source_map(outputFile)
%GENERATE_TABLE_FIGURE_SOURCE_MAP Rebuild the table/figure source-map XLSX.
%
% Usage:
%   generate_table_figure_source_map
%   generate_table_figure_source_map('/path/to/table_figure_source_map.xlsx')
%
% The workbook is stored in XLSX format for readability. The source data
% are kept here so the documented source map can be regenerated without
% relying on a hand-edited spreadsheet.

if nargin < 1 || isempty(outputFile)
    scriptDir = fileparts(mfilename('fullpath'));
    rootDir = char(java.io.File(fullfile(scriptDir, '..', '..')).getCanonicalPath());
    outputFile = fullfile(rootDir, 'docs', 'table_figure_source_map.xlsx');
end

rows = table_figure_source_map_rows();
outputDir = fileparts(outputFile);
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

tmpDir = tempname;
mkdir(tmpDir);
cleanupObj = onCleanup(@() cleanup_temp_dir(tmpDir)); %#ok<NASGU>
csvFile = fullfile(tmpDir, 'table_figure_source_map.csv');
writecell(rows, csvFile);

libreOffice = find_libreoffice();
if ~isempty(libreOffice)
    cmd = sprintf('env -u LD_LIBRARY_PATH %s --headless --convert-to xlsx --outdir %s %s', ...
        shell_quote(libreOffice), shell_quote(tmpDir), shell_quote(csvFile));
    [status, msg] = system(cmd);
    if status == 0
        generated = fullfile(tmpDir, 'table_figure_source_map.xlsx');
        if exist(generated, 'file')
            copyfile(generated, outputFile, 'f');
            normalize_source_map_xlsx(outputFile);
            return
        end
    else
        warning('SourceMap:LibreOfficeFailed', ...
            'LibreOffice conversion failed, falling back to MATLAB writecell: %s', strtrim(msg));
    end
end

writecell(rows, outputFile);
end

function rows = table_figure_source_map_rows()
rows = {
    'Item', 'Type', 'Paper title', 'Output file(s) after fast run', 'Replication action', 'Generating code', 'Data/source artifact(s)', 'Notes', '', '', '';
    'Figure 1', 'Figure', 'U.S. apparel consumption/imports', 'output/figures/paper/figure_01_apparel_consumption_imports.pdf; output/figures/paper/figure_01_apparel_consumption_imports.eps', 'GENERATED: run_all_replication reads the public BEA/WTO workbook and recreates the paper figure.', 'code/matlab/run_all_replication.m generate_figure_01()', 'data/BEA_and_WTO--trade_and_production_aggregates/data_figure_1_updated.xlsx', 'Generated from included public aggregate apparel consumption/import data.', '', '', '';
    'Figure 2', 'Figure', 'Number of suppliers, 1996-2011', 'output/figures/paper/figure_02_number_of_suppliers.eps', 'COPIED DISCLOSED ARTIFACT: run_all_replication copies the Census disclosure-approved EPS file from the data folder.', 'code/Stata_LFTTD_code/13_lfttd_aggregates.do ; Census disclosure request output', 'data/Census_LFTTD--disclosed_statistics_and_graphs/CES_disclosed_files/1109_tybout_release_req5623_20170228/NoSeller_1996_2011.eps', 'Disclosure-approved supplier-count figure.', '', '', '';
    'Figure 3', 'Figure', 'Number of suppliers by country', 'output/figures/paper/figure_03_suppliers_by_country.eps', 'COPIED DISCLOSED ARTIFACT: run_all_replication copies the Census disclosure-approved EPS file from the data folder.', 'code/Stata_LFTTD_code/12_lfttd_aggregates_by_country.do; Census disclosure request output', 'data/Census_LFTTD--disclosed_statistics_and_graphs/CES_disclosed_files/1109_tybout_release_req5623_20170228/NoSeller_by_country_1996_2011.eps', 'Disclosure-approved country supplier-count figure.', '', '', '';
    'Figure 4', 'Figure', 'Value of imports by country', 'output/figures/paper/figure_04_import_value_by_country.eps', 'GENERATED: run_all_replication reads the Department of Commerce workbook and recreates the paper figure.', 'code/matlab/run_all_replication.m generate_figure_04()', 'data/Dept_of_Commerce--apparel_imports_by_origin/imp_apparel_cty.xls', 'Generated from included public country import-value data.', '', '', '';
    'Figure 5', 'Figure', 'Industry structure', 'Manuscript schematic only; no output file generated by MATLAB driver', 'NOT GENERATED: conceptual manuscript schematic; no MATLAB generation code found in package.', 'Manuscript source / corrected paper in docs/EJTX_2026_replication.pdf and docs/EJTX_2026_replication.tex', 'Conceptual figure, not data-generated', 'No MATLAB generation code found in package; not a computational result.', '', '', '';
    'Figure 6', 'Figure', 'Number of buyers, related party versus arm''s length trade', 'output/figures/paper/figure_06_buyers_related_arm_length.eps', 'COPIED DISCLOSED ARTIFACT: run_all_replication copies the Census disclosure-approved EPS file from the data folder.', 'code/Stata_LFTTD_code/14_lfttd_aggregates_by_related.do; Census disclosure request output', 'data/Census_LFTTD--disclosed_statistics_and_graphs/CES_disclosed_files/1109_tybout_release_req5623_20170228/NoBuyer_by_related_1996_2011.eps', 'Disclosure-approved buyer-count figure by relationship status.', '', '', '';
    'Figure 7', 'Figure', 'Model structure', 'Manuscript schematic only; no output file generated by MATLAB driver', 'NOT GENERATED: conceptual model schematic; no MATLAB generation code found in package.', 'Manuscript source / corrected LaTeX in docs/EJTX_2026_replication.tex', 'Conceptual figure, not data-generated', 'No MATLAB generation code found in package; not a computational result.', '', '', '';
    'Figure 8', 'Figure', 'Data-based versus model-based moments', 'output/figures/paper/figure_08_baseline_model_fit.pdf', 'GENERATED: run_all_replication runs the baseline plot_fit.m code at the saved baseline parameter vector and writes the Figure 8 PDF during the fast run.', 'code/matlab/run_all_replication.m generate_figure_08(); code/matlab/baseline_no_NsNb_target/plot_fit.m', 'code/matlab/baseline_no_NsNb_target/results/se_results_baseline_no_M_target.mat; data/Census_LFTTD--disclosed_statistics_and_graphs/', 'Generated from source code in fast mode; exact baseline fit is also re-evaluated in output/logs/exact_fit_checks.log.', '', '', '';
    'Figure 9', 'Figure', 'Buyer Profit and Search Cost Heterogeneity', 'output/figures/paper/figure_09_buyer_profit_search_cost_heterogeneity.png', 'GENERATED: run_all_replication solves the steady-state model at the saved parameter vector and writes this figure during the fast run.', 'code/matlab/run_all_replication.m generate_figure_09(); code/matlab/baseline_counterfactuals_July_2024/steady state summary/main.m', 'code/matlab/baseline_no_NsNb_target/results/se_results_no_M_target.mat', 'Regenerated by solving the steady-state model at the saved parameter vector and plotting the two paper panels.', '', '', '';
    'Figure 10', 'Figure', 'Buyers and Suppliers Accumulation of Connections', 'output/figures/paper/figure_10_buyers_suppliers_connection_accumulation.png', 'GENERATED: run_all_replication solves/simulates the baseline life-cycle model at the saved parameter vector and writes this figure during the fast run.', 'code/matlab/run_all_replication.m generate_figure_10(); code/matlab/baseline_counterfactuals_July_2024/baseline simulation/main.m', 'code/matlab/baseline_no_NsNb_target/results/se_results_no_M_target.mat; code/matlab/baseline_counterfactuals_July_2024/baseline simulation/05_avg_number_partners_by_yr_in_market.xls', 'Regenerated by solving the baseline model at the saved parameter vector and plotting buyer/supplier life-cycle growth.', '', '', '';
    'Figure 11', 'Figure', 'Trump Tariff Effects on Supplier Dynamics', 'output/figures/paper/figure_11a_trump_tariff_supplier_dynamics.png; output/figures/paper/figure_11b_event_study_china_vs_other_exporters.png', 'GENERATED: panel (a) is generated by run_all_replication from the saved tariff transition sequence using the plotting logic from trump tariff/main.m; the full transition solve can be rerun separately and compared with audit_tariff_transition.m. Panel (b) is generated by the packaged Stata event-study script.', 'Panel (a): code/matlab/run_all_replication.m generate_figure_11a(); code/matlab/baseline_counterfactuals_July_2024/trump tariff/main.m plotting logic; transition audit: code/matlab/audit_tariff_transition.m. Panel (b): code/Stata_figure11b_event_study/event_study.do.', 'Panel (a): code/matlab/baseline_counterfactuals_July_2024/trump tariff/dynamics_tariff.mat; code/matlab/baseline_no_NsNb_target/results/se_results_no_M_target.mat. Panel (b): data/US_ITC_figure11b_event_study/merged_apparel_2017_2025_importVQT.dta; data/US_ITC_figure11b_event_study/model_prediction.dta.', 'Panel (a) is regenerated in fast mode and can be separately audited by rerunning the full tariff transition. Panel (b) requires Stata with ebalance ftools require and reghdfe installed.', '', '', '';
    'Figure 12', 'Figure', 'Mechanical model estimated search intensities', 'output/figures/paper/figure_12_mechanical_search_intensities.png', 'GENERATED: run_all_replication uses load_best_mechanical_estimate.m and the Figure 12 plotting code ported from build_mechanical_appendix_outputs.m to write the PNG during the fast run.', 'code/matlab/run_all_replication.m generate_mechanical_outputs(); code/matlab/mechanical_model/build_mechanical_appendix_outputs.m; code/matlab/mechanical_model/load_best_mechanical_estimate.m', 'code/matlab/mechanical_model/data/mechanical_best_estimate.csv; code/matlab/mechanical_model/results/', 'Generated from the included mechanical estimate in fast mode.', '', '', '';
    'Figure 13', 'Figure', 'Match Shock Model: Data-based versus model-based moments', 'output/figures/paper/figure_13_match_shock_model_fit.png', 'GENERATED: run_all_replication evaluates the MP match-shock model at the saved RA-supplied parameter vector and runs the MP plot_fit.m source code in a temporary working copy.', 'code/matlab/run_all_replication.m generate_figure_13(); code/matlab/baseline_counterfactuals_July_2024/MP model/calibration_no_gamma_s/plot_fit.m', 'code/matlab/baseline_counterfactuals_July_2024/MP model/Results2026/Baseline_MP/results/se_results_est_eta.mat', 'Generated from source code in fast mode using the RA-supplied full-precision MP parameter artifact; MP objective values are separately re-evaluated in the fit log.', '', '', '';
    'Table 1', 'Table', 'Year-to-year transition rates: buyers per supplier', 'output/tables/paper/table_01_transition_buyers_per_supplier_paper_display.csv; output/tables/paper/table_01_transition_buyers_per_supplier.xls', 'COPIED + PAPER-DISPLAY CSV: run_all_replication copies the disclosure-approved source table file and writes a paper-display CSV with the accepted-manuscript labels/rounding.', 'code/Stata_LFTTD_code/05_lfttd_NumSellerBuyer_transition_matrix.do; code/matlab/*/data_moments_baseline.m', 'data/Census_LFTTD--disclosed_statistics_and_graphs/CES_disclosed_files/1109_tybout_release_req5488_20170109/transition_matrix_num_buyers_per_seller.xls', 'Paper-display CSV matches Table 1 at displayed precision; raw disclosed source file is retained as a support artifact.', '', '', '';
    'Table 2', 'Table', 'Year-to-year transition rates: suppliers per buyer', 'output/tables/paper/table_02_transition_suppliers_per_buyer_paper_display.csv; output/tables/paper/table_02_transition_suppliers_per_buyer.xls', 'COPIED + PAPER-DISPLAY CSV: run_all_replication copies the disclosure-approved source table file and writes a paper-display CSV with the accepted-manuscript labels/rounding.', 'code/Stata_LFTTD_code/05_lfttd_NumSellerBuyer_transition_matrix.do; code/matlab/*/data_moments_baseline.m', 'data/Census_LFTTD--disclosed_statistics_and_graphs/CES_disclosed_files/1109_tybout_release_req5488_20170109/transition_matrix_num_sellers_per_buyer.xls', 'Paper-display CSV matches Table 2 at displayed precision; raw disclosed source file is retained as a support artifact.', '', '', '';
    'Table 3', 'Table', 'Firm distributions by partner counts, 2011', 'output/tables/paper/table_03_firm_distributions_by_partner_counts_2011.csv; output/tables/paper/table_03_partner_count_distribution_source.xls', 'COPIED + PAPER-DISPLAY CSV: run_all_replication copies the disclosure-approved source file and writes a paper-display CSV for Table 3.', 'code/Stata_LFTTD_code/03_lfttd_dist_NumSeller_per_buyer.do; code/Stata_LFTTD_code/04_lfttd_dist_NumBuyer_per_seller.do; code/matlab/*/data_moments_baseline.m', 'data/Census_LFTTD--disclosed_statistics_and_graphs/CES_disclosed_files/1109_tybout_release_req5952_20170808/05_avg_number_partners_by_yr_in_market.xls', 'Paper-display CSV matches Table 3 at displayed precision.', '', '', '';
    'Table 4', 'Table', 'Buyers'' imports per supplier and within-buyer supplier shares', 'output/tables/paper/table_04_buyers_imports_per_supplier_and_supplier_shares.csv', 'PAPER-DISPLAY CSV: run_all_replication writes a paper-display CSV for Table 4 from the disclosed paper values used by the model moment code.', 'code/matlab/run_all_replication.m write_disclosed_paper_display_tables(); code/matlab/*/data_moments_baseline.m', 'data/Census_LFTTD--disclosed_statistics_and_graphs/; code pending disclosure, U.S. Census Bureau', 'Paper-display CSV matches Table 4 at displayed precision.', '', '', '';
    'Table 5', 'Table', 'Cost and Distributional Parameters', 'output/tables/paper/table_05_cost_distributional_parameters.csv; output/tables/paper/generated_standard_errors_at_saved_parameters.csv; output/tables/paper/model_fit_checks_for_tables_05_09_10_11_12.csv; output/logs/exact_fit_checks.log; output/logs/standard_error_generation.log', 'GENERATED: run_all_replication writes a standalone Table 5 CSV from the saved baseline parameter vector; it regenerates standard errors by running baseline std_errors.m in a temporary working copy and separately re-evaluates the baseline objective at that vector.', 'code/matlab/run_all_replication.m write_standalone_model_tables(); code/matlab/generate_standard_errors_at_saved_parameters.m; code/matlab/baseline_no_NsNb_target/std_errors.m; code/matlab/baseline_no_NsNb_target/objective.m; code/matlab/audit_report_values.m', 'code/matlab/baseline_no_NsNb_target/results/se_results_baseline_no_M_target.mat', 'Standalone CSV contains paper-reported rounded values and generated full-precision values; regenerated standard errors match the revised manuscript at displayed precision.', '', '', '';
    'Table 6', 'Table', 'Counterfactual: Interpreting market developments', 'output/tables/paper/table_06_market_developments_counterfactual.tex', 'GENERATED: run_all_replication runs transition_dynamics.m, which calls summary_ss.m to write counterfactual_table_2026.tex, then copies that newly generated LaTeX fragment into output/tables/paper/.', 'code/matlab/baseline_counterfactuals_July_2024/transition dynamics/transition_dynamics.m; summary_ss.m', 'code/matlab/baseline_counterfactuals_July_2024/transition dynamics/', 'Generated from source code in fast mode at the included saved baseline parameter vector.', '', '', '';
    'Table 7', 'Table', 'Counterfactual: Trump Section 301 Tariff', 'output/tables/paper/table_07_trump_section_301_tariff.tex', 'GENERATED: run_all_replication runs the Trump tariff main.m source code through the table-writing section, then copies the newly generated counterfactual_tariff_table.tex into output/tables/paper/.', 'code/matlab/baseline_counterfactuals_July_2024/trump tariff/main.m', 'code/matlab/baseline_counterfactuals_July_2024/trump tariff/', 'Generated from source code in fast mode. The expensive tariff transition-dynamics loop is skipped after Table 7 is written in fast mode; it can be rerun and compared with code/matlab/audit_tariff_transition.m.', '', '', '';
    'Table 8', 'Table', 'Effect of 2004 policy shock, baseline model and mechanical model', 'output/tables/paper/table_08_mechanical_policy_shock.tex', 'GENERATED: run_all_replication runs mechanical_counterfactual_main.m, which calls summary_mechanical_policy_shock.m to write counterfactual_table_policy_only.tex, then copies that newly generated table into output/tables/paper/.', 'code/matlab/run_all_replication.m generate_mechanical_outputs(); code/matlab/mechanical_model/mechanical_counterfactual_main.m; code/matlab/mechanical_model/summary_mechanical_policy_shock.m', 'code/matlab/mechanical_model/data/mechanical_best_estimate.csv; baseline counterfactual outputs', 'Generated from source code in fast mode using the included mechanical estimate and generated Table 6 baseline counterfactual table as an input.', '', '', '';
    'Table 9', 'Table', 'Parameter Estimates and Fit for Baseline, Match Shock, and No Dispersion', 'output/tables/paper/table_09_mp_model_parameters_and_fit.csv; output/tables/paper/generated_standard_errors_at_saved_parameters.csv; output/tables/paper/model_fit_checks_for_tables_05_09_10_11_12.csv; output/logs/standard_error_generation.log', 'GENERATED: run_all_replication writes the paper-shaped Table 9 CSV from saved full-precision parameter vectors; it regenerates baseline and MP standard errors by running std_errors.m in temporary working copies and re-evaluates MP objective values at the saved vectors.', 'code/matlab/run_all_replication.m write_standalone_model_tables(); code/matlab/generate_standard_errors_at_saved_parameters.m; code/matlab/baseline_counterfactuals_July_2024/MP model/calibration_no_gamma_s/std_errors.m; code/matlab/baseline_counterfactuals_July_2024/MP model/calibration_no_gamma_s/objective.m; code/matlab/audit_report_values.m', 'code/matlab/baseline_counterfactuals_July_2024/MP model/Results2026/; code/matlab/baseline_no_NsNb_target/results/se_results_baseline_no_M_target.mat', 'Regenerated Results2026 Match Shock objective', ' match-death moment', ' parameter estimates', ' and standard errors match current docs/EJTX_2026_replication.tex at displayed precision.';
    'Table 10', 'Table', 'Comparison of Heterogeneous Death Hazard Model with Baseline', 'output/tables/paper/table_10_heterogeneous_death_hazard_comparison.csv; output/tables/paper/generated_standard_errors_at_saved_parameters.csv; output/tables/paper/model_fit_checks_for_tables_05_09_10_11_12.csv; output/logs/exact_fit_checks.log; output/logs/standard_error_generation.log', 'GENERATED: run_all_replication writes a standalone Table 10 CSV from the baseline and heterogeneous match-death saved parameter vectors; it regenerates standard errors by running std_errors.m in temporary working copies and re-evaluates the heterogeneous objectives.', 'code/matlab/run_all_replication.m write_standalone_model_tables(); code/matlab/generate_standard_errors_at_saved_parameters.m; code/matlab/heterogeneous_death_haz/sellers_only/std_errors.m; code/matlab/heterogeneous_death_haz/sellers_only/objective.m; code/matlab/audit_report_values.m', 'code/matlab/baseline_no_NsNb_target/results/se_results_baseline_no_M_target.mat; code/matlab/heterogeneous_death_haz/sellers_only/results/se_results_hetero.mat', 'Standalone CSV contains paper-reported rounded values and generated full-precision values; regenerated objectives and standard errors match the revised manuscript at displayed precision.', '', '', '';
    'Table 11', 'Table', 'Model vs Data-based Moments', 'output/tables/paper/table_11_model_vs_data_based_moments.csv; output/tables/paper/model_fit_checks_for_tables_05_09_10_11_12.csv; output/logs/exact_fit_checks.log', 'GENERATED: run_all_replication writes a standalone Table 11 CSV from the heterogeneous match-death saved/generated moment artifact; exact-fit checks re-evaluate the same model quantities.', 'code/matlab/run_all_replication.m write_standalone_model_tables(); code/matlab/heterogeneous_death_haz/sellers_only/sim_moments_hetero.m; code/matlab/audit_report_values.m', 'code/matlab/heterogeneous_death_haz/sellers_only/results/se_results_hetero.mat; code/matlab/heterogeneous_death_haz/sellers_only/disclosed_moments/', 'Standalone CSV contains the data and model-based match-death moments reported in Table 11.', '', '', '';
    'Table 12', 'Table', 'MSM results (EJTX moments vs. our AAR model)', 'output/tables/paper/table_12_aar_parameter_estimates.csv; table_12_aar_moment_comparison.csv; model_fit_checks_for_tables_05_09_10_11_12.csv', 'GENERATED CHECK SUMMARY + GENERATED CSV ARTIFACTS: run_all_replication runs generate_comparison_outputs.m to write AAR comparison CSVs and re-evaluates the AAR fit in the exact-fit routine.', 'code/matlab/AAR/comparison/scripts/generate_comparison_outputs.m; code/matlab/AAR/estimation/run_estimation.m', 'code/matlab/AAR/estimation/output/estimation_results.mat; code/matlab/AAR/comparison/tables/', 'Generated AAR table artifacts plus exact-fit verification in the log/CSV.', '', '', '';
    'Table 13', 'Table', 'Section 6.1 experiment: EJTX vs. our AAR model (% changes)', 'output/tables/paper/table_13_aar_policy_shock_benchmark_comparison.csv; table_13_aar_policy_shock_comparison.csv', 'GENERATED: run_all_replication runs generate_comparison_outputs.m, which calls the AAR policy-shock source code and writes the Table 13 CSV artifacts before copying them into output/tables/paper/.', 'code/matlab/AAR/comparison/scripts/generate_comparison_outputs.m; code/matlab/AAR/counterfactuals/policy_shock/run_policy_shock_counterfactual.m', 'code/matlab/AAR/counterfactuals/policy_shock/; code/matlab/AAR/comparison/tables/', 'Generated from source code in fast mode using included AAR estimation and baseline-moment artifacts.', '', '', ''
    };
end

function pathOut = find_libreoffice()
candidates = {'libreoffice', 'soffice'};
pathOut = '';
for i = 1:numel(candidates)
    [status, result] = system(sprintf('command -v %s', candidates{i}));
    if status == 0 && ~isempty(strtrim(result))
        pathOut = strtrim(result);
        return
    end
end
end

function q = shell_quote(s)
q = ['''' strrep(char(s), '''', '''"''"''') ''''];
end

function cleanup_temp_dir(tmpDir)
if exist(tmpDir, 'dir')
    rmdir(tmpDir, 's');
end
end

function normalize_source_map_xlsx(xlsxFile)
% LibreOffice can make tiny platform-dependent width/height changes.
% Normalize the simple sheet layout so regenerated files match the
% maintained workbook layout.
layoutDir = tempname;
mkdir(layoutDir);
cleanupObj = onCleanup(@() cleanup_temp_dir(layoutDir)); %#ok<NASGU>
unzip(xlsxFile, layoutDir);

sheetFile = fullfile(layoutDir, 'xl', 'worksheets', 'sheet1.xml');
txt = fileread(sheetFile);
cols = ['<cols>' ...
    '<col collapsed="false" customWidth="true" hidden="false" outlineLevel="0" max="1" min="1" style="0" width="9.14"/>' ...
    '<col collapsed="false" customWidth="true" hidden="false" outlineLevel="0" max="2" min="2" style="0" width="6.57"/>' ...
    '<col collapsed="false" customWidth="true" hidden="false" outlineLevel="0" max="3" min="3" style="0" width="62.57"/>' ...
    '<col collapsed="false" customWidth="true" hidden="false" outlineLevel="0" max="4" min="4" style="0" width="243.15"/>' ...
    '<col collapsed="false" customWidth="true" hidden="false" outlineLevel="0" max="5" min="5" style="0" width="247.86"/>' ...
    '<col collapsed="false" customWidth="true" hidden="false" outlineLevel="0" max="7" min="6" style="0" width="296.29"/>' ...
    '<col collapsed="false" customWidth="true" hidden="false" outlineLevel="0" max="8" min="8" style="0" width="169"/>' ...
    '<col collapsed="false" customWidth="true" hidden="false" outlineLevel="0" max="9" min="9" style="0" width="19.29"/>' ...
    '<col collapsed="false" customWidth="true" hidden="false" outlineLevel="0" max="10" min="10" style="0" width="18.71"/>' ...
    '<col collapsed="false" customWidth="true" hidden="false" outlineLevel="0" max="11" min="11" style="0" width="67.57"/>' ...
    '</cols>'];
txt = regexprep(txt, '<cols>.*?</cols>', cols);
txt = regexprep(txt, '(<row[^>]*?) ht="[^"]+"', '$1 ht="12.75"');

fid = fopen(sheetFile, 'w');
if fid == -1
    error('Could not write %s.', sheetFile);
end
cleanupFid = onCleanup(@() fclose(fid)); %#ok<NASGU>
fwrite(fid, txt);
clear cleanupFid;

if exist(xlsxFile, 'file')
    delete(xlsxFile);
end
cmd = sprintf('cd %s && zip -qr %s .', shell_quote(layoutDir), shell_quote(xlsxFile));
[status, msg] = system(cmd);
if status ~= 0
    error('Failed to rebuild %s after layout normalization: %s', xlsxFile, strtrim(msg));
end
end
