// This script executes the dofiles used for apparel sector analysis

/* $Data includes all original data, translated from SAS to STATA files */
/* $Output and $OutputTemp includes all generated data sets. all are generated by do files */
/* $Result includes all .xlsx .csv and other tables which will be included in documents */
/* $OutputLog includes all log files by stata */

clear all
set more off
capture log close

global Data       "/projects/data"

global Dofile     "/projects/programs/zyy/Two-sided_Match/Stata/Dofile"
global Output     "/projects/programs/zyy/Two-sided_Match/Stata/Output"
global OutputTemp "/projects/programs/zyy/Two-sided_Match/Stata/OutputTemp"
global Result     "/projects/programs/zyy/Two-sided_Match/Stata/Result"
global OutputLog  "/projects/programs/zyy/Two-sided_Match/Stata/OutputLog"

//log using "$Dofile/do_apparel_shell.log", replace

// create the folder if it does not exists
capture mkdir $Output
capture mkdir $OutputTemp
capture mkdir $Result
capture mkdir $OutputLog
/*
// The raw data input of "01_lfttd_imp_apparel_1996_2011.do" 
// does not exist anymore after RDC restructured the data files
** do "$Dofile/01_lfttd_imp_apparel_1996_2011.do"

// Start with "02_lfttd_imp_apparel_alpha_id_exp.do", 
// the input data "lfttd_m_apparel_`y'.dta" has a copy 
// in the folder "projects/data/lfttd_apparel"
do "$Dofile/02_lfttd_imp_apparel_alpha_id_exp.do"

do "$Dofile/03_lfttd_dist_NumSeller_per_buyer.do"

do "$Dofile/04_lfttd_dist_NumBuyer_per_seller.do"

do "$Dofile/05_lfttd_NumSellerBuyer_transition_matrix.do"

do "$Dofile/06_lfttd_NumSellerBuyer_transition_matrix_bootstrap.do"

do "$Dofile/07_lfttd_duration.do"

do "$Dofile/08_lfttd_duration_hazardrate.do"

do "$Dofile/09_apparel_payoff_fn.do"

do "$Dofile/10_lfttd_imp_apparel_transaction_level.do"

do "$Dofile/11_lfttd_imp_apparel_transaction_time_interval.do"

do "$Dofile/12_lfttd_aggregates_by_country.do"

do "$Dofile/13_lfttd_aggregates.do"

do "$Dofile/14_lfttd_aggregates_by_related.do"

// The raw data input of "01_lfttd_imp_apparel_1996_2011.do" 
// may change after RDC restructured the data files
// The original output has a copy in the folder "projects/data/busname2/ssl_apparel"
// Use this one to ensure that the results are consistent.
** do "$Dofile/15_clean_ssl_na.do"

do "$Dofile/16_ssl_cfn6_name_naics_wide_list.do"

do "$Dofile/17_lfttd_aggregates_by_retailer_wholesaler.do"
*/

***************************************************
****  Appendix
***************************************************
/*
do "$Dofile/A1_1_lfttd_aggregates_topcountry_vs_others.do"

do "$Dofile/A1_2_NoSeller_Top10Country_vs_Others.do"

do "$Dofile/A2_lfttd_ssl_matched_nonmatched.do"

do "$Dofile/A3_lfttd_Top20ImportersName.do"

do "$Dofile/A4_Transition_matrix_2001_and_Large_importers.do"

do "$Dofile/A5_lfttd_ssl_ExitingImporters_ExitingBusiness.do"

do "$Dofile/A6_transition_matrix_adjusted_alpha.do"

do "$Dofile/A7_lfttd_imp_apparel_statistics.do"

do "$Dofile/A8_Buyer_Seller_Match_ProductVarietyConcentration.do"

do "$Dofile/A9_lfttd_tenure_of_match.do"
*/
do "$Dofile/A10_lfttd_tenure_of_BuyerSeller.do"
/*
do "$Dofile/A11_lfttd_asm_cmf_apparel_import_penetration.do"

do "$Dofile/A12_1_lfttd_imp_apparel_imports_turnover_decomposition.do"

do "$Dofile/A12_2_lfttd_imp_apparel_imports_turnover_decomposition.do"

do "$Dofile/A12_3_lfttd_imp_apparel_imports_turnover_decomposition.do"

do "$Dofile/A13_Regression_logLinear_Num_sellers_per_buyer.do"
*/
do "$Dofile/A14_lfttd_seller_shares.do" 

log close
