// This script executes the dofiles used for apparel sector analysis

/* $Data includes all original data, translated from SAS to STATA files */
/* $Output and $OutputTemp includes all generated data sets. all are generated by do files */
/* $Result includes all .xlsx .csv and other tables which will be included in documents */
/* $OutputLog includes all log files by stata */

clear all
set more off
capture log close

global Data       "/projects/data"

global Dofile     "/projects/programs/zyy/Two-sided_Match/Stata/Dofile"
global Output     "/projects/programs/zyy/Two-sided_Match/Stata/Output"
global OutputTemp "/projects/programs/zyy/Two-sided_Match/Stata/OutputTemp"
global Result     "/projects/programs/zyy/Two-sided_Match/Stata/Result"
global OutputLog  "/projects/programs/zyy/Two-sided_Match/Stata/OutputLog"

//log using "$Dofile/do_apparel_shell.log", replace

// create the folder if it does not exists
capture mkdir $Output
capture mkdir $OutputTemp
capture mkdir $Result
capture mkdir $OutputLog

// The raw data input of "01_lfttd_imp_apparel_1996_2011.do" 
// does not exist anymore after RDC restructured the data files
** do "$Dofile/01_lfttd_imp_apparel_1996_2011.do"

// Start with "02_lfttd_imp_apparel_alpha_id_exp.do", 
// the input data "lfttd_m_apparel_`y'.dta" has a copy 
// in the folder "projects/data/lfttd_apparel"

do "$Dofile/02_lfttd_imp_apparel_alpha_id_exp.do"

do "$Dofile/03_lfttd_dist_NumSeller_per_buyer.do"

do "$Dofile/04_lfttd_dist_NumBuyer_per_seller.do"

do "$Dofile/05_lfttd_NumSellerBuyer_transition_matrix.do"

do "$Dofile/07_lfttd_duration.do"

do "$Dofile/12_lfttd_aggregates_by_country.do"

do "$Dofile/13_lfttd_aggregates.do"

do "$Dofile/14_lfttd_aggregates_by_related.do"

do "$Dofile/A10_lfttd_tenure_of_BuyerSeller.do"

do "$Dofile/A14_lfttd_seller_shares.do" 

log close
